### ISSUE TITLE
Script with the times command fails when run with selenium-side-runner

### ISSUE THREAD

**Issue by mark-stonehenge** [SeleniumHQ/selenium-ide#1000]
## 🐛 Bug Report
The times command fails if its target value comes from a variable when run with the selenium-side-runner tool. 
- This error does not happen when the script is run directly from the IDE.
- This error does not happen in the side-runner when the times command's target value is a hard-coded number

## To Reproduce
This script does not open a web page - it uses the times and echo commands to write a number to the log three times. I originally observed this issue when I was creating a script for a production issue.
- Create a script that uses the times command to run the echo command three times
- Use a variable to hold the value for the number of times to repeat the echo command. Set the variable by either the execute script or store commands. 
- Run the script in the IDE and it runs successfully to completion
- Run the script in the selenium-side-runner

## Expected behavior
- When run via the selenium-side-runner, the script successfully to completion

## Actual results
- The script fails immediately after being started.
- Here is the output
  ● Test suite failed to run
    SyntaxError: C:\Users\mabrennan\Desktop\side-suite-Sandbox\commons.js: Unexpected token, expected ";" (6:18)

      4 |   vars["iteration_counter"] = `3`;
      5 |   vars["counter"] = await driver.executeScript(`return 0`);
    > 6 |   const times = $ {
        |                   ^
      7 |     vars.iteration_counter
      8 |   };
      9 |   for (let i = 0; i < times; i++) {

      at Parser.raise (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:3831:17)
      at Parser.unexpected (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:5143:16)
      at Parser.semicolon (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:5131:40)
      at Parser.parseVarStatement (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7715:10)
      at Parser.parseStatementContent (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7310:21)
      at Parser.parseStatement (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7243:17)
      at Parser.parseBlockOrModuleBlockBody (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7810:25)
      at Parser.parseBlockBody (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7797:10)
      at Parser.parseBlock (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:7786:10)
      at Parser.parseFunctionBody (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/lib/index.js:6876:24)

## Project file reproducing this issue
[Sandbox.zip](https://github.com/SeleniumHQ/selenium-ide/files/4416771/Sandbox.zip)

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser: Microsoft Edge (chromium)
Browser Version:

**Comment by WolfPD** [comment]
still not fixed:

... Unexpected token, expected ";" (6:18)

      4 |   vars["vara"] = await driver.executeScript(`return 5`);
      5 |   //
    > 6 |   const times = $ {
        |                   ^
      7 |     vars.vara
      8 |   };
      9 |   for (let i = 0; i < times; i++) {

**Comment by PaulJrBertucci** [comment]
I, too, am seeing this one trying to run a .side in selenium-side-runner where one of the tests has a "times" loop on a var:

```
SyntaxError: /home/taloras/Downloads/side-suite-IPDdevsite/commons.js: Unexpected token, expected ";" (265:18)
     
      263 |   });
      264 |   console.log(`${vars.Del}`);
    > 265 |   const times = $ {
          |                   ^
      266 |     vars.Del
      267 |   };
      268 |   for (let i = 0; i < times; i++) {
```

**Comment by scottdnz** [comment]
A workaround for this for the selenium-siderunner is to use a while loop instead, e.g.   
instead of "times", "${maxLoopNumber}"  
try  
"while", "${maxLoopNumber} < ${iteratorNumber}"
 
Example screenshot:  

![selenium_loopb](https://user-images.githubusercontent.com/700396/132284169-1af89cbc-77e9-442a-9dab-9ade088d3bd6.png)
