### ISSUE TITLE
When run via PowerShell, utils.js throws error on mkdir if test has been run before with code EEXIST

### ISSUE THREAD

**Issue by marknoble** [SeleniumHQ/selenium-ide#1078]
## 🐛 Bug Report

Running the same .side file repeatedly via an elevated PowerShell prompt results in the following error and the temporary working directory cannot be deleted because it is in use by a process after the test is complete.

PS C:\Selenium> selenium-side-runner .\Test.side
info:    Running ./Test.side
internal/fs/utils.js:259
    throw err;
    ^

Error: EEXIST: file already exists, mkdir 'side-suite-Test'
    at Object.mkdirSync (fs.js:940:3)
    at runProject (C:\Users\mark\AppData\Roaming\npm\node_modules\selenium-side-runner\dist\index.js:240:15)
    at runAll (C:\Users\mark\AppData\Roaming\npm\node_modules\selenium-side-runner\dist\index.js:345:10)
    at Object.<anonymous> (C:\Users\mark\AppData\Roaming\npm\node_modules\selenium-side-runner\dist\index.js:390:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: 'side-suite-Test'
}
PS C:\Selenium> Remove-Item -Recurse -Force .\side-suite-Test\
Remove-Item : Cannot remove item C:\Selenium\side-suite-Test\: The process cannot access the file 'C:\Selenium\side-suite-Test\' because it is being used by another process.
At line:1 char:1
+ Remove-Item -Recurse -Force .\side-suite-Test\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Selenium\side-suite-Test\:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand

## To Reproduce

1. Run any simple Test.side file via PowerShell window with elevated permissions
Upon successful completion, re-run Test.side file

## Expected behavior

I expected the test to be able to run repeatedly without error.

## Project file reproducing this issue (highly encouraged)

Project file `.side` that reproduces this issue.
[Test.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/4833325/Test.side.txt)
(This is just an example, but any `.side` file should be sufficient)

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  3.17.0
Node version: v14.4.0
Browser: Chrome
Browser Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by marknoble** [comment]
Hello [Triage folks](https://www.selenium.dev/structure/#docs_site_committers), I noticed this issue hasn't been assigned yet. Anything I can do to help this process along?
@AutomatedTester 
@diemol
@manoj9788
@raju249
@pujagani
@SalmonMode

**Comment by AutomatedTester** [comment]
unfortunately, IDE has been currently deprioritised since we don't have people to work on it while we try finished off things for Selenium 4.
