### ISSUE TITLE
selenium-side-runner how to wait for the page to load

### ISSUE THREAD

**Issue by bianyucheng-eb** [SeleniumHQ/selenium-ide#1087]
## 💬 Questions and Help

  When I use selenium-side-runner to automate testing, some websites will fail to test because they cannot be selected because of the overlay. I conducted several tests on the .side file that caused this error, and not every time it failed, but this still affected my project. I think selenium-side-runner can wait for the page to load and execute the test.

my .side file
```
{
  "id": "63de462b-342a-4057-b4fb-f37762d3063a",
  "version": "2.0",
  "name": "FAQ6",
  "url": "url",
  "tests": [{
    "id": "1c7f0ad7-47d4-4d31-b985-d59b58972ed8",
    "name": "FAQ6",
    "commands": [{
      "id": "865adcec-6e74-4c67-989c-19facae6e419",
      "comment": "",
      "command": "open",
      "target": "/faq/",
      "targets": [],
      "value": ""
    }, {
      "id": "e36703e3-29ab-4155-8de2-4ee6522014c7",
      "comment": "",
      "command": "setWindowSize",
      "target": "1050x843",
      "targets": [],
      "value": ""
    }, {
      "id": "36280940-97ed-4dc4-823f-78f7a26c504c",
      "comment": "",
      "command": "click",
      "target": "linkText=Build a Resume",
      "targets": [
        ["linkText=Build a Resume", "linkText"],
        ["css=.col-md-3 .col-md-12:nth-child(2) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Build a Resume')]", "xpath:link"],
        ["xpath=//a[contains(@href, '/resumes/edit/')]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Build a Resume')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "dcff0562-1707-46be-adf1-13dcafda0edf",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["1c7f0ad7-47d4-4d31-b985-d59b58972ed8"]
  }],
  "urls": ["url"],
  "plugins": []
}
```

error message
```
ElementClickInterceptedError: element click intercepted: Element <a href="/resumes/edit/">...</a> is not clickable at point (407, 833). Other element would receive the click: <div class="loading-mask">...</div>
  (Session info: headless chrome=83.0.4103.61)
celeryworker_1       | 
  12 |   };
  13 |   await driver.wait(until.elementLocated(By.linkText(`Build a Resume`)), configuration.timeout);
> 14 |   await driver.findElement(By.linkText(`Build a Resume`)).then(element => {
  celeryworker_1       |          |   ^
  15 |     return element.click();
  16 |   });
  17 | }

  at Object.throwDecodedError (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
  at parseHttpResponse (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
  at Executor.execute (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)
  at mixin.execute (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
  at Object.<anonymous>.tests.FAQ6 (commons.js:14:3)
  at Object.<anonymous> (DefaultSuite.test.js:11:5)
```

**Comment by jeremylorino** [comment]
Just to be clear I would not consider this a bug.

I suggest waiting for the overlay to disappear before taking action on elements. This is a very common situation that is specific to each AUT. Thus requires an additional check for the [non]existence of an element.

This can be solved by a separate "helper test" that performs the checks and can be called using the `run` command.
