### ISSUE TITLE
selenium-side-runner fails with "Unexpected token" when using "times" with a variable

### ISSUE THREAD

**Issue by dttrian** [SeleniumHQ/selenium-ide#1158]
## 🐛 Bug Report

When using a variable as an argument to the "times" command, selenium-side-runner fails with an "Unexpected token" error, while the same test runs fine on Selenium IDE.

This is the output produced by selenium-side-runner:
```
info:    Running Test.side

 RUNS  ./DefaultSuite.test.js
 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    SyntaxError: C:\Users\Utente\Downloads\side-suite-Test\commons.js: Unexpected token, expected ";" (5:18)

      3 | tests["Untitled"] = async (driver, vars, opts = {}) => {
      4 |   vars["times_to_run"] = `3`;
    > 5 |   const times = $ {
        |                   ^
      6 |     vars.times_to_run
      7 |   };
      8 |   for (let i = 0; i < times; i++) {

      at Parser._raise (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/error.js:60:45)
      at Parser.raiseWithData (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/error.js:55:17)
      at Parser.raise (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/error.js:39:17)
      at Parser.unexpected (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/util.js:139:16)
      at Parser.semicolon (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/util.js:109:40)
      at Parser.parseVarStatement (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/statement.js:701:10)
      at Parser.parseStatementContent (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/statement.js:217:21)
      at Parser.parseStatement (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/statement.js:157:17)
      at Parser.parseBlockOrModuleBlockBody (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/statement.js:877:25)
      at Parser.parseBlockBody (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/@babel/parser/src/parser/statement.js:847:10)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.59s
Ran all test suites.
```

## To Reproduce

1. create a test that uses the times command with a variable as an argument (instead of an hard coded value) - as the one provided in the "Project file reproducing this issue" section
1. run it throught selenium-side-runner

## Expected behavior

The test should run fine just as it happens with Selenium IDE.

## Project file reproducing this issue

```
{
  "id": "faebaf4d-6444-4800-b1cb-e8089cf4c083",
  "version": "2.0",
  "name": "Test",
  "url": "http://www.google.com",
  "tests": [{
    "id": "830da3c1-134f-4dce-842f-c0e500d9d2a1",
    "name": "Untitled",
    "commands": [{
      "id": "15f195f6-8143-4427-92d0-b734024d4d70",
      "comment": "",
      "command": "store",
      "target": "3",
      "targets": [],
      "value": "times_to_run"
    }, {
      "id": "536df865-5a88-43aa-b908-0c28dc1f2278",
      "comment": "",
      "command": "times",
      "target": "${times_to_run}",
      "targets": [],
      "value": ""
    }, {
      "id": "c24e1a04-f9e7-446b-a88a-d29c4122ea38",
      "comment": "",
      "command": "echo",
      "target": "Test",
      "targets": [],
      "value": ""
    }, {
      "id": "88a4057b-e859-40cb-b72e-d996d56b34fb",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "ee870e7a-4908-4f5d-a7ce-b73a8be5e614",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["830da3c1-134f-4dce-842f-c0e500d9d2a1"]
  }],
  "urls": [],
  "plugins": []
}
```

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  3.17.0
Node version: v12.18.2
Browser:
Browser Version: 86.0.4240.193 (64 bit)

**Comment by dttrian** [comment]
While this is imho a bug, for anyone with the same problem it's worth mentioning that a workaround is replacacing times with a while and a counter variable.

Here is an example:
```
{
  "id": "faebaf4d-6444-4800-b1cb-e8089cf4c083",
  "version": "2.0",
  "name": "Test",
  "url": "http://www.google.com",
  "tests": [{
    "id": "830da3c1-134f-4dce-842f-c0e500d9d2a1",
    "name": "Untitled",
    "commands": [{
      "id": "15f195f6-8143-4427-92d0-b734024d4d70",
      "comment": "",
      "command": "store",
      "target": "10",
      "targets": [],
      "value": "times_to_run"
    }, {
      "id": "b2c73d0c-3d6f-4ca1-9b4b-6296ea7ff7a8",
      "comment": "",
      "command": "executeScript",
      "target": "return 0",
      "targets": [],
      "value": "i"
    }, {
      "id": "536df865-5a88-43aa-b908-0c28dc1f2278",
      "comment": "",
      "command": "while",
      "target": "${i} < ${times_to_run}",
      "targets": [],
      "value": ""
    }, {
      "id": "c24e1a04-f9e7-446b-a88a-d29c4122ea38",
      "comment": "",
      "command": "echo",
      "target": "Test ${i}",
      "targets": [],
      "value": ""
    }, {
      "id": "ed113f1e-ee37-4877-b415-31246b48df12",
      "comment": "",
      "command": "executeScript",
      "target": "return ${i} + 1",
      "targets": [],
      "value": "i"
    }, {
      "id": "88a4057b-e859-40cb-b72e-d996d56b34fb",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "ee870e7a-4908-4f5d-a7ce-b73a8be5e614",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["830da3c1-134f-4dce-842f-c0e500d9d2a1"]
  }],
  "urls": ["http://www.google.com/"],
  "plugins": []
}
```

**Comment by KennethSJiang** [comment]
running into the same issue for my tests. js ${variable} doesn't seem to be working with the selenium-side-runner, but it works with selenium IDE. please help
