### ISSUE TITLE
Unable to locate 'selenium-core-scripts\selenium-browserdetect.js' when executing 'yarn start'

### ISSUE THREAD

**Issue by DevSnobo** [SeleniumHQ/selenium-ide#118]
Version: 1.0.3
Yarn version: 1.5.1
OS: Win10 (1709 Update)

I am trying to build the IDE using Yarn. After figuring out that I needed a seperate Git installation, I could get as far as installing dependecies, but when calling 'yarn start', these errors are shown:

`ERROR in ./src/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\closure-loader\index.js:113:19)
    at C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\closure-loader\index.js:47:22
    at tryCatcher (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\promise_array.js:126:19)
    at MappingPromiseArray._promiseFulfilled (C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\node_modules\bluebird\js\release\map.js:101:18)
 @ ./src/locatorBuilders.js 1:180-209
 @ ./src/record.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./record

ERROR in [copy-webpack-plugin] unable to locate 'selenium-core-scripts/htmlutils.js' at 'C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\src\selenium-core-scripts\htmlutils.js'

ERROR in [copy-webpack-plugin] unable to locate 'selenium-core-scripts/selenium-browserdetect.js' at 'C:\Users\user\Documents\selenium-ide-1.0.3\packages\selenium-ide\src\selenium-core-scripts\selenium-browserdetect.js'`

I hope someone can point me in the right direction, since I am a noob when it comes to package managers etc. Thanks

**Comment by corevo** [comment]
It seems you haven't ran peru sync

Cheers,
Tom

**Comment by Jongkeun** [comment]
Hi @DevSnobo .
Is it clear this problem?
I had same problem with you and I tried to find out what is cause.

In conclusion, the libraries that are obtained using `peru` don't support windows.
`peru sync` is fine.

I tested using the `selenium-ide` directory that is normal on Linux.
And copy this directory to my Windows PC.
If I use ` .\selenium-ide\packages\selenium-ide\build` folder that was built on Linux for extension,
it has no problem and works fine.
However I build again with same code and library on Windows, the same problem occurs with you.
So I am working using Ubuntu.🤣

**Comment by corevo** [comment]
Maybe we should look for a different tool, even though the plan is to use the monorepo's toolchain, we are at the moment putting a hurdle on people who do want to contribute.  
Maybe there is something we're missing, the [readme](https://github.com/buildinspace/peru#installation) specifically indicates that peru supports Windows.

**Comment by corevo** [comment]
wdym aren't normal?

**Comment by Jongkeun** [comment]
I don't know the exact cause, but I think it is different from Linux when I build it.
I mean, the code is normal, but it seems different during the build process.

**Comment by corevo** [comment]
I'll take a look, worst case we can clone with depth 0 and copy the directories on Windows instead.

**Comment by Jongkeun** [comment]
And `yarn start` doesn't work anymore on Windows.
Because windows has no `env` like Linux.

**Comment by corevo** [comment]
Closing as there is not response from thread opener.
