### ISSUE TITLE
Can't find closure dependency bot on yarn install

### ISSUE THREAD

**Issue by ildelian** [SeleniumHQ/selenium-ide#1225]
I am trying to download and compile the TAG 3.17.0 of Selenium, and I am getting an error when launch "yarn build" command.

## Environment

OS: Linux Alpine 3.12 (From a Docker Image)
Selenium IDE Version: 3.17.0

## Installation and compile Steps:
apk update
apk add zip unzip bash python3 py3-pip git
pip install peru 
pip install sync

cd /usr/src/dist/selenium-ide-3.17.0
yarn install
yarn build

The error is:
ERROR in ./content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/index.js:114:19)

Yarn build LOG:

RUN yarn build:
yarn run v1.22.5
$ lerna run build --ignore selenium-ide-extension-boilerplate
lerna notice cli v3.4.3
lerna info filter [ '!selenium-ide-extension-boilerplate' ]
lerna info Executing command in 14 packages: "yarn run build"
$ babel -d dist src --ignore=__test__
Successfully compiled 3 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 4 files with Babel.
$ yarn run browserify src/index.js -s browser-webdriver -o build/webdriver.js
$ /usr/src/dist/selenium-ide-3.17.0/node_modules/.bin/browserify src/index.js -s browser-webdriver -o build/webdriver.js
$ babel -d dist src --ignore=__test__
Successfully compiled 14 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 3 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 3 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 5 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 5 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 5 files with Babel.
$ babel -d dist src --ignore=__test__
Successfully compiled 5 files with Babel.
$ rollup -c
$ babel -d dist src --ignore=__test__
Successfully compiled 1 file with Babel.
$ babel -d dist src --ignore=src/__test__
Successfully compiled 9 files with Babel.
lerna ERR! yarn run build exited 2 in 'selenium-ide-extension'
lerna ERR! yarn run build stdout:
$ rm -rf build && env NODE_ENV=production webpack
[copy-webpack-plugin] WARNING - unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js' at '/usr/src/dist/selenium-ide-3.17.0/packages/selenium-ide/selenium/selenium-core-scripts/selenium-browserdetect.js'
Hash: ff08eb911ec07a65faf4
Version: webpack 3.12.0
Time: 106324ms
                                      Asset       Size  Chunks                    Chunk Names
media/selenium_blue_white32@3x.84ab23d0.svg    3.62 kB          [emitted]
            media/selenium-ide.52b672fb.ttf    7.74 kB          [emitted]
            media/selenium-ide.18592ff3.svg    22.5 kB          [emitted]
                                  record.js    88.5 kB       0  [emitted]         record
                                playback.js      98 kB       1  [emitted]         playback
                                     neo.js    2.71 MB       2  [emitted]  [big]  neo
                              background.js    84.9 kB       3  [emitted]         background
                                   atoms.js    29.2 kB       4  [emitted]         atoms
                               polyfills.js    10.6 kB       5  [emitted]         polyfills
                                  escape.js    2.98 kB       6  [emitted]         escape
                              record.js.map     293 kB       0  [emitted]         record
                            playback.js.map     393 kB       1  [emitted]         playback
                                 neo.js.map    9.98 MB       2  [emitted]         neo
                          background.js.map     298 kB       3  [emitted]         background
                               atoms.js.map     110 kB       4  [emitted]         atoms
                           polyfills.js.map    56.6 kB       5  [emitted]         polyfills
                              escape.js.map    14.3 kB       6  [emitted]         escape
                           vendor/global.js  825 bytes          [emitted]
                                  prompt.js    7.25 kB          [emitted]
                              highlight.css  952 bytes          [emitted]
                          ../bootstrap.html    1.57 kB          [emitted]
                          ../indicator.html    1.68 kB          [emitted]
                               indicator.js    1.08 kB          [emitted]
                           ../manifest.json    1.76 kB          [emitted]
                 ../icons/icon_light128.png    5.31 kB          [emitted]
                   ../icons/icon_menu16.png  552 bytes          [emitted]
                   ../icons/icon_menu32.png    1.22 kB          [emitted]
                   ../icons/icon_menu64.png    2.76 kB          [emitted]
                       ../icons/icon128.png    5.88 kB          [emitted]
                        ../icons/icon16.png  612 bytes          [emitted]
                        ../icons/icon32.png    1.29 kB          [emitted]
                        ../icons/icon64.png    2.91 kB          [emitted]
                              ../index.html  315 bytes          [emitted]
  [27] ./common/utils.js 349 bytes {0} {2} {3} [built]
  [66] ./content/closure-polyfill.js 5.32 kB {4} [built] [failed] [1 error]
 [127] ./content/commands-api.js 5.4 kB {1} [built]
 [130] ./content/escape.js 4.97 kB {1} {6} [built]
 [192] ./content/selenium-api.js 121 kB {1} [built]
 [292] multi ./content/setup 28 bytes {5} [built]
 [293] ./content/setup.js 1.03 kB {5} [built]
 [294] multi ./content/commands-api 28 bytes {1} [built]
 [300] multi ./background/background 28 bytes {3} [built]
 [301] ./background/background.js 5.87 kB {3} [built]
 [302] multi ./content/record 28 bytes {0} [built]
 [303] ./content/record.js 17.7 kB {0} [built]
 [306] multi ./content/escape 28 bytes {6} [built]
 [307] multi react-hot-loader/patch ./neo/containers/Root 40 bytes {2} [built]
 [311] ./neo/containers/Root/index.jsx 1.36 kB {2} [built]
    + 1066 hidden modules

WARNING in ./neo/stores/seed.js
17:496-509 "export 'CommandsArray' was not found in '../models/Command'
 @ ./neo/stores/seed.js
 @ ./neo/containers/Panel/index.jsx
 @ ./neo/containers/Root/index.jsx
 @ multi react-hot-loader/patch ./neo/containers/Root

WARNING in ./neo/stores/seed.js
17:535-548 "export 'CommandsArray' was not found in '../models/Command'
 @ ./neo/stores/seed.js
 @ ./neo/containers/Panel/index.jsx
 @ ./neo/containers/Root/index.jsx
 @ multi react-hot-loader/patch ./neo/containers/Root

ERROR in ./content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/index.js:114:19)
    at /usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/index.js:48:22
    at tryCatcher (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/map.js:108:18)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise_array.js:127:19)
    at MappingPromiseArray._promiseFulfilled (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/map.js:108:18)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
 @ ./content/commands-api.js 16:46-73
 @ multi ./content/commands-api

ERROR in [copy-webpack-plugin] unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js' at '/usr/src/dist/selenium-ide-3.17.0/packages/selenium-ide/selenium/selenium-core-scripts/selenium-browserdetect.js'
Child html-webpack-plugin for "../index.html":
     1 asset
       [0] /usr/src/dist/selenium-ide-3.17.0/node_modules/html-webpack-plugin/lib/loader.js!./neo/index.html 726 bytes {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 2.

lerna ERR! yarn run build exited 2 in 'selenium-ide-extension'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 2

**Comment by ildelian** [comment]
` > [11/11] RUN yarn build:
#15 1.161 yarn run v1.22.5
#15 1.299 $ lerna run build --ignore selenium-ide-extension-boilerplate
#15 2.004 lerna notice cli v3.4.3
#15 2.159 lerna info filter [ '!selenium-ide-extension-boilerplate' ]
#15 2.187 lerna info Executing command in 14 packages: "yarn run build"
#15 6.103 $ babel -d dist src --ignore=__test__
#15 6.103 Successfully compiled 3 files with Babel.
#15 6.708 $ babel -d dist src --ignore=__test__
#15 6.708 Successfully compiled 4 files with Babel.
#15 12.12 $ yarn run browserify src/index.js -s browser-webdriver -o build/webdriver.js
#15 12.12 $ /usr/src/dist/selenium-ide-3.17.0/node_modules/.bin/browserify src/index.js -s browser-webdriver -o build/webdriver.js
#15 14.36 $ babel -d dist src --ignore=__test__
#15 14.36 Successfully compiled 14 files with Babel.
#15 18.31 $ babel -d dist src --ignore=__test__
#15 18.31 Successfully compiled 3 files with Babel.
#15 18.82 $ babel -d dist src --ignore=__test__
#15 18.82 Successfully compiled 3 files with Babel.
#15 20.39 $ babel -d dist src --ignore=__test__
#15 20.39 Successfully compiled 5 files with Babel.
#15 20.42 $ babel -d dist src --ignore=__test__
#15 20.42 Successfully compiled 5 files with Babel.
#15 23.74 $ babel -d dist src --ignore=__test__
#15 23.74 Successfully compiled 5 files with Babel.
#15 24.04 $ babel -d dist src --ignore=__test__
#15 24.04 Successfully compiled 5 files with Babel.
#15 26.83 $ rollup -c
#15 28.62 $ babel -d dist src --ignore=__test__
#15 28.62 Successfully compiled 1 file with Babel.
#15 29.15 $ babel -d dist src --ignore=src/__test__
#15 29.15 Successfully compiled 9 files with Babel.
#15 137.6 lerna ERR! yarn run build exited 2 in 'selenium-ide-extension'
#15 137.6 lerna ERR! yarn run build stdout:
#15 137.6 $ rm -rf build && env NODE_ENV=production webpack
#15 137.6 [copy-webpack-plugin] WARNING - unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js' at '/usr/src/dist/selenium-ide-3.17.0/packages/selenium-ide/selenium/selenium-core-scripts/selenium-browserdetect.js'
#15 137.6 Hash: ff08eb911ec07a65faf4
#15 137.6 Version: webpack 3.12.0
#15 137.6 Time: 106324ms
#15 137.6                                       Asset       Size  Chunks                    Chunk Names
#15 137.6 media/selenium_blue_white32@3x.84ab23d0.svg    3.62 kB          [emitted]
#15 137.6             media/selenium-ide.52b672fb.ttf    7.74 kB          [emitted]
#15 137.6             media/selenium-ide.18592ff3.svg    22.5 kB          [emitted]
#15 137.6                                   record.js    88.5 kB       0  [emitted]         record
#15 137.6                                 playback.js      98 kB       1  [emitted]         playback
#15 137.6                                      neo.js    2.71 MB       2  [emitted]  [big]  neo
#15 137.6                               background.js    84.9 kB       3  [emitted]         background
#15 137.6                                    atoms.js    29.2 kB       4  [emitted]         atoms
#15 137.6                                polyfills.js    10.6 kB       5  [emitted]         polyfills
#15 137.6                                   escape.js    2.98 kB       6  [emitted]         escape
#15 137.6                               record.js.map     293 kB       0  [emitted]         record
#15 137.6                             playback.js.map     393 kB       1  [emitted]         playback
#15 137.6                                  neo.js.map    9.98 MB       2  [emitted]         neo
#15 137.6                           background.js.map     298 kB       3  [emitted]         background
#15 137.6                                atoms.js.map     110 kB       4  [emitted]         atoms
#15 137.6                            polyfills.js.map    56.6 kB       5  [emitted]         polyfills
#15 137.6                               escape.js.map    14.3 kB       6  [emitted]         escape
#15 137.6                            vendor/global.js  825 bytes          [emitted]
#15 137.6                                   prompt.js    7.25 kB          [emitted]
#15 137.6                               highlight.css  952 bytes          [emitted]
#15 137.6                           ../bootstrap.html    1.57 kB          [emitted]
#15 137.6                           ../indicator.html    1.68 kB          [emitted]
#15 137.6                                indicator.js    1.08 kB          [emitted]
#15 137.6                            ../manifest.json    1.76 kB          [emitted]
#15 137.6                  ../icons/icon_light128.png    5.31 kB          [emitted]
#15 137.6                    ../icons/icon_menu16.png  552 bytes          [emitted]
#15 137.6                    ../icons/icon_menu32.png    1.22 kB          [emitted]
#15 137.6                    ../icons/icon_menu64.png    2.76 kB          [emitted]
#15 137.6                        ../icons/icon128.png    5.88 kB          [emitted]
#15 137.6                         ../icons/icon16.png  612 bytes          [emitted]
#15 137.6                         ../icons/icon32.png    1.29 kB          [emitted]
#15 137.6                         ../icons/icon64.png    2.91 kB          [emitted]
#15 137.6                               ../index.html  315 bytes          [emitted]
#15 137.6   [27] ./common/utils.js 349 bytes {0} {2} {3} [built]
#15 137.6   [66] ./content/closure-polyfill.js 5.32 kB {4} [built] [failed] [1 error]
#15 137.6  [127] ./content/commands-api.js 5.4 kB {1} [built]
#15 137.6  [130] ./content/escape.js 4.97 kB {1} {6} [built]
#15 137.6  [192] ./content/selenium-api.js 121 kB {1} [built]
#15 137.6  [292] multi ./content/setup 28 bytes {5} [built]
#15 137.6  [293] ./content/setup.js 1.03 kB {5} [built]
#15 137.6  [294] multi ./content/commands-api 28 bytes {1} [built]
#15 137.6  [300] multi ./background/background 28 bytes {3} [built]
#15 137.6  [301] ./background/background.js 5.87 kB {3} [built]
#15 137.6  [302] multi ./content/record 28 bytes {0} [built]
#15 137.6  [303] ./content/record.js 17.7 kB {0} [built]
#15 137.6  [306] multi ./content/escape 28 bytes {6} [built]
#15 137.6  [307] multi react-hot-loader/patch ./neo/containers/Root 40 bytes {2} [built]
#15 137.6  [311] ./neo/containers/Root/index.jsx 1.36 kB {2} [built]
#15 137.6     + 1066 hidden modules
#15 137.6
#15 137.6 WARNING in ./neo/stores/seed.js
#15 137.6 17:496-509 "export 'CommandsArray' was not found in '../models/Command'
#15 137.6  @ ./neo/stores/seed.js
#15 137.6  @ ./neo/containers/Panel/index.jsx
#15 137.6  @ ./neo/containers/Root/index.jsx
#15 137.6  @ multi react-hot-loader/patch ./neo/containers/Root
#15 137.6
#15 137.6 WARNING in ./neo/stores/seed.js
#15 137.6 17:535-548 "export 'CommandsArray' was not found in '../models/Command'
#15 137.6  @ ./neo/stores/seed.js
#15 137.6  @ ./neo/containers/Panel/index.jsx
#15 137.6  @ ./neo/containers/Root/index.jsx
#15 137.6  @ multi react-hot-loader/patch ./neo/containers/Root
#15 137.6
#15 137.6 ERROR in ./content/closure-polyfill.js
#15 137.6 Module build failed: Error: Can't find closure dependency bot
#15 137.6     at replaceRequire (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/index.js:114:19)
#15 137.6     at /usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/index.js:48:22
#15 137.6     at tryCatcher (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/util.js:16:23)
#15 137.6     at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:547:31)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6     at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
#15 137.6     at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
#15 137.6     at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
#15 137.6     at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6     at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
#15 137.6     at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
#15 137.6     at MappingPromiseArray.PromiseArray._resolve (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise_array.js:127:19)
#15 137.6     at MappingPromiseArray._promiseFulfilled (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/map.js:108:18)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:609:26)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6     at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
#15 137.6     at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
#15 137.6     at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
#15 137.6     at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6     at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
#15 137.6     at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
#15 137.6     at MappingPromiseArray.PromiseArray._resolve (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise_array.js:127:19)
#15 137.6     at MappingPromiseArray._promiseFulfilled (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/map.js:108:18)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:609:26)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6     at Promise._settlePromises (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:729:18)
#15 137.6     at Promise._fulfill (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:673:18)
#15 137.6     at Promise._resolveCallback (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:466:57)
#15 137.6     at Promise._settlePromiseFromHandler (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:559:17)
#15 137.6     at Promise._settlePromise (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:604:18)
#15 137.6     at Promise._settlePromise0 (/usr/src/dist/selenium-ide-3.17.0/node_modules/closure-loader/node_modules/bluebird/js/release/promise.js:649:10)
#15 137.6  @ ./content/commands-api.js 16:46-73
#15 137.6  @ multi ./content/commands-api
#15 137.6
#15 137.6 ERROR in [copy-webpack-plugin] unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js' at '/usr/src/dist/selenium-ide-3.17.0/packages/selenium-ide/selenium/selenium-core-scripts/selenium-browserdetect.js'
#15 137.6 Child html-webpack-plugin for "../index.html":
#15 137.6      1 asset
#15 137.6        [0] /usr/src/dist/selenium-ide-3.17.0/node_modules/html-webpack-plugin/lib/loader.js!./neo/index.html 726 bytes {0} [built]
#15 137.6        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
#15 137.6        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
#15 137.6         + 1 hidden module
#15 137.6 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#15 137.6
#15 137.6 lerna ERR! yarn run build stderr:
#15 137.6 error Command failed with exit code 2.
#15 137.6
#15 137.6 lerna ERR! yarn run build exited 2 in 'selenium-ide-extension'
#15 137.6 error Command failed with exit code 2.
#15 137.6 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 2`

**Comment by ildelian** [comment]
The problem seems to be related with the "closure-polyfill.js" file.
In there, there are a library called "bot"

export var bot = {}
goog.require('bot')
goog.require('bot.action')
goog.require('bot.events')
goog.require('bot.locators')
goog.require('bot.inject')
goog.require('bot.inject.cache')
goog.require('bot.userAgent')
goog.require('bot.Keyboard')

But, when closure try so swap the goog.require() with a CommonJS require() call, "bot" can not be found as a deoendency.
There are some special thing to do about this library?

**Comment by ildelian** [comment]
Hi.
I had misunderstood this installation line: 
"Install the dependencies `peru sync`"

I understood that I have to install "peru" and "sync" from python package manager

I think that the line is a bit confusing, is better to put: 
Install the dependencies running the command `peru sync`
