### ISSUE TITLE
Selenium IDE v4 bombs when running a suite, then running a single test in the same IDE session

### ISSUE THREAD

**Issue by clfordhub** [SeleniumHQ/selenium-ide#1545]
I ran a suite of tests, then attempted to re-run just a single test that failed, but it seemed like the playback didn't fully close between runs.  I wasn't able to run just the failed single test as the IDE thought the playback was still running.  Can we fully close the playback runner after a suite completes?

Logs:
[2022-10-18 14:37:44.210] [error] (node:16128) UnhandledPromiseRejectionWarning: Error: Can't start playback while a different playback is running
    at Playback._beforePlay (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:325:13)
    at Playback.play (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:162:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `Selenium IDE --trace-warnings ...` to show where the warning was created)
[2022-10-18 14:37:44.210] [error] (node:16128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
[2022-10-18 14:38:52.809] [debug] Playing state changed prep
[2022-10-18 14:38:52.816] [info]  [PROCESS] Unhandled Promise Rejection
[2022-10-18 14:38:52.816] [info]  - - - - - - - - - - - - - - - - - - -
[2022-10-18 14:38:52.816] [info]  Error: Can't start playback while a different playback is running
    at Playback._beforePlay (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:325:13)
    at Playback.play (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:162:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-18 14:38:52.817] [info]  - -
[2022-10-18 14:38:52.817] [error] (node:16128) UnhandledPromiseRejectionWarning: Error: Can't start playback while a different playback is running
    at Playback._beforePlay (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:325:13)
    at Playback.play (C:\Users\Administrator\AppData\Local\Programs\@seleniumhqselenium-ide\resources\app.asar\build\webpack:\side-runtime\src\playback.ts:162:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-18 14:38:52.818] [error] (node:16128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)

**Comment by toddtarsi** [comment]
@clfordhub - Plz let me know if you're still seeing this. I just ran a crashing suite a few times and then played tests without issue, but maybe there is a bit more to this.

**Comment by clfordhub** [comment]
This is still happening for me.  
Error log shows:  [2022-11-10 08:36:07.788] [error] (node:17012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)

**Comment by toddtarsi** [comment]
@clfordhub - Beforehand, how does the suite fail? Is it like a step timed out issue or something more particular? I think the specific error type might cause a different code path, because just failing to find an element to click doesn't do it.
