### ISSUE TITLE
selenium-side-runner fails to find the proper chromedriver when it's installed using NPM

### ISSUE THREAD

**Issue by cosmo0** [SeleniumHQ/selenium-ide#1594]
## 🐛 Bug Report

The NPM packages for ChromeDriver installs multiple "executable-looking" files, and the runner fails.

## To Reproduce

````cmd
npm install -g selenium-side-runner
npm install -g chromedriver
````

Restart the console then try to run `selenium-side-runner myproject.side`

Among the errors, there's a hint that it finds two executable-looking file, because there's "chromedriver" (without extension) and "chromedriver.cmd" on the stacktrace, on two lines.

````
info: Running test Connexion
debug: Playing state changed prep for test Connexion
info: Building driver for chrome
  console.log
     The ChromeDriver could not be found on the current PATH, trying Selenium Manager

      at new ServiceBuilder (node_modules/selenium-webdriver/chrome.js:163:15)

  console.error
    Error: The specified executable path does not exist: D:\Users\cosmo\AppData\Roaming\npm\chromedriver
    D:\Users\cosmo\AppData\Roaming\npm\chromedriver.cmd
        at new Object.<anonymous>.DriverService.Builder (D:\Users\cosmo\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\remote\index.js:322:13)
at new ServiceBuilder (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\chromium.js:203:5)
        at new ServiceBuilder (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\chrome.js:183:5)
        at Function.getDefaultService (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\chrome.js:264:12)
        at Function.createSession (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\chromium.js:686:49)
        at Function.createSession (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\chrome.js:255:13)
        at createDriver (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\index.js:149:33)
        at Builder.build (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\selenium-webdriver\index.js:677:16)
        at WebDriverExecutor.init (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\@seleniumhq\side-runtime\src\webdriver.ts:200:10)
        at Playback.init (D:\Users\tbroust\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\@seleniumhq\side-runtime\src\playback.ts:140:25)
````

And sure enough, **when renaming "chromedriver" (without extension) to something else, the project is run**.

Also, not installing npm's version of ChromeDriver and downloading it manually/setting the path works fine.

## Expected behavior

The runner should pick one of the multiple files, and not try to run both at once.

## Project file reproducing this issue (highly encouraged)

Any random file will do, it happens in the runner.

## Environment

OS: Windows 10 Entreprise
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.42
Node version: v16.11.1

**Comment by toddtarsi** [comment]
@cosmo0 - Looking at that stack trace, is this more of an issue with selenium-webdriver? I'm not sure why everyone thinks using npm to install chromedriver is good either. That things supposed to be on your main $PATH variable, not stuffed in a random node_modules folder. How is that supposed to work?

**Comment by toddtarsi** [comment]
I'm not going to close this issue. It washes up here enough that it might be worth it to me to write some wacky stuff to make it work, but I'm not rushing to it because it's basically me eating the cost of people doing a poor job of properly installing chromedriver.

**Comment by cosmo0** [comment]
@toddtarsi People use npm because it's the "official" way to install the drivers : https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner

The drivers ARE in the PATH variable. It's just that two of them are there (because of the way it's installed through npm).

My best guess is that it searches for the exe with some pattern, finds both files (with and without extension), stores them in a variable with a line break (or an array, hey it's JS), and then it tries to use this multi-line string: https://github.com/SeleniumHQ/selenium/blob/8141f82923a448725a5266789aed01130dab37ec/javascript/node/selenium-webdriver/remote/index.js#L321

Maybe the simplest fix would be to change the documentation, as it also causes other weird stuff: for instance, if it finds the driver on the PATH, it ignores the `-c "chromeOptions.binary"` argument. So I can't have a broken driver on the path for reasons outside of my control, and a working driver in my git repo.

**Comment by cosmo0** [comment]
Apparently it searches for `chromedriver.exe` and does not care if there's a valid `.cmd` (or .bat or whatever) forwarding the commands https://github.com/SeleniumHQ/selenium/blob/8141f82923a448725a5266789aed01130dab37ec/javascript/node/selenium-webdriver/chrome.js#L141

I would think the `io.findInFiles` method is probably broken in the specific scenario where chromedriver is installed through npm https://github.com/SeleniumHQ/selenium/blob/8141f82923a448725a5266789aed01130dab37ec/javascript/node/selenium-webdriver/io/index.js#L210

**Comment by toddtarsi** [comment]
@cosmo0 - I didn't write v3 or the docs, but thanks for pointing that out. That explains things a bit haha. Also, yeah, the level of overrides going on sounds off. I'd be okay with adding a bit of sugar around this to try and find chromedriver via npm and use it if available. If possible, would you be able to run side runner with the debug flags on (`-dD`) and let me know what the configuration looks like at the selenium-webdriver boundary. Basically, I want to make sure the config flags and stuff aren't getting messed up at the ide boundary, since I have a lot more control over that than I do over driver bindings.

That should give me some information to try and find immediately actionable fixes for me to do.

**Comment by cosmo0** [comment]
Oh yeah the "capabilities" shows that it KNOWS I have a `.side.yml` file, and it just... ignores it. Doesn't care at all. Crashes as usual, trying to run the driver from `D:\Users\cosmo\AppData\Roaming\npm\` instead of reading the conf. But it's a different problem, since removing the `.side.yml` file changes nothing to the behavior.

Just running `npm uninstall -g chromedriver` and it works fine again. So weird.

> selenium-side-runner .\MyProject.side -dD

````
Configuration: {
  baseUrl: '',
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      binary: 'D:\\Dev\\MyProject\\Selenium\\drivers\\chromedriver\\chromedriver.exe'
    },
    firefoxOptions: {
      binary: 'D:\\Dev\\MyProject\\Selenium\\drivers\\geckodriver\\geckodriver.exe'
    },
    edgeOptions: {
      binary: 'D:\\Dev\\MyProject\\Selenium\\drivers\\edgedriver\\msedgedriver.exe'
    }
  },
  debug: true,
  debugStartup: true,
  filter: '.*',
  force: undefined,
  maxWorkers: 8,
  projects: [ 'D:\\Dev\\MyProject\\Selenium\\MyProject.side' ],
  proxyOptions: {},
  proxyType: undefined,
  retries: 0,
  runId: '4ad766dde8e87ee4e0df967a244f544e',
  path: 'D:\\Users\\cosmo\\AppData\\Roaming\\npm\\node_modules\\',
  server: '',
  timeout: 15000
}
Jest command: D:\Users\cosmo\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\.bin\jest.cmd [
  '--config=D:\\Users\\cosmo\\AppData\\Roaming\\npm\\node_modules\\selenium-side-runner\\jest.config.js',
  '--maxConcurrency=8',
  '',
  '--runTestsByPath',
  'D:\\Users\\cosmo\\AppData\\Roaming\\npm\\node_modules\\selenium-side-runner\\dist\\main.test.js'
] {
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'D:\\Users\\cosmo\\AppData\\Roaming',
  'asl.log': 'Destination=file',
  ASPNETCORE_ENVIRONMENT: 'Development',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: '133083953844789294',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'PRS-B9YVZ93',
  ComSpec: 'C:\\windows\\system32\\cmd.exe',
  CONDA_PROMPT_MODIFIER: 'False',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  HOMEDRIVE: 'Z:',
  HOMEPATH: '\\',
  HOMESHARE: '\\\\network.priv\\individuel$\\cosmo',
  JAVA_HOME: 'C:\\Program Files\\ojdkbuild\\java-15-openjdk-15.0.2-1\\',
  LOCALAPPDATA: 'D:\\Users\\cosmo\\AppData\\Local',
  LOGONSERVER: '\\\\ZEUS',
  NUMBER_OF_PROCESSORS: '8',
  OJDKBUILD_JAVA_HOME: 'C:\\Program Files\\ojdkbuild\\java-15-openjdk-15.0.2-1\\',
  OneDrive: 'D:\\Users\\cosmo\\OneDrive',
  OneDriveConsumer: 'D:\\Users\\cosmo\\OneDrive',
  OS: 'Windows_NT',
  Path: 'C:\\Program Files\\PowerShell\\7;C:\\Program Files\\Microsoft\\jdk-11.0.16.101-hotspot\\bin;C:\\Program Files\\Python3\\Scripts\\;C:\\Program Files\\Python3\\;C:\\Program Files\\AdoptOpenJDK\\jre-16.0.1.9-hotspot\\bin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\ojdkbuild\\java-15-openjdk-15.0.2-1\\missioncontrol\\;C:\\Program Files\\ojdkbuild\\java-15-openjdk-15.0.2-1\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\CMake\\bin;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\Git\\cmd;D:\\Users\\cosmo\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Users\\cosmo\\AppData\\Local\\Programs\\Fiddler;D:\\Users\\cosmo\\.dotnet\\tools;D:\\Users\\cosmo\\AppData\\Roaming\\npm;D:\\Users\\cosmo\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Program Files\\PuTTY',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL',
  POSH_GIT_ENABLED: 'True',
  POSH_THEME: 'D:\\Users\\cosmo\\Documents\\PowerShell\\custom.omp.json',
  POSH_THEMES_PATH: 'D:\\Users\\cosmo\\AppData\\Local\\Programs\\oh-my-posh\\themes',
  POWERLINE_COMMAND: 'oh-my-posh',
  POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Enterprise',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '8c01',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PSModulePath: 'D:\\Users\\cosmo\\Documents\\PowerShell\\Modules;C:\\Program Files\\PowerShell\\Modules;c:\\program files\\powershell\\7\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'D:\\Users\\Public',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\windows',
  TEMP: 'D:\\Users\\cosmo\\AppData\\Local\\Temp',
  TMP: 'D:\\Users\\cosmo\\AppData\\Local\\Temp',
  USERDNSDOMAIN: 'NETWORK.PRIV',
  USERDOMAIN: 'NETWORK',
  USERDOMAIN_ROAMINGPROFILE: 'NETWORK',
  USERNAME: 'cosmo',
  USERPROFILE: 'D:\\Users\\cosmo',
  windir: 'C:\\windows',
  WSLENV: 'WT_SESSION::WT_PROFILE_ID',
  WT_PROFILE_ID: '{574e775e-4f2a-5b96-ac1e-a2962a402336}',
  WT_SESSION: 'ff19b2bf-df8e-405e-a0c2-93a4f0ba5801',
  ZES_ENABLE_SYSMAN: '1',
  SE_CONFIGURATION: '{"baseUrl":"","capabilities":{"browserName":"chrome","chromeOptions":{"binary":"D:\\\\Dev\\\\MyProject\\\\Selenium\\\\drivers\\\\chromedriver\\\\chromedriver.exe"},"firefoxOptions":{"binary":"D:\\\\Dev\\\\MyProject\\\\Selenium\\\\drivers\\\\geckodriver\\\\geckodriver.exe"},"edgeOptions":{"binary":"D:\\\\Dev\\\\MyProject\\\\Selenium\\\\drivers\\\\edgedriver\\\\msedgedriver.exe"}},"debug":true,"debugStartup":true,"filter":".*","maxWorkers":8,"projects":["D:\\\\Dev\\\\MyProject\\\\Selenium\\\\MyProject.side"],"proxyOptions":{},"retries":0,"runId":"4ad766dde8e87ee4e0df967a244f544e","path":"D:\\\\Users\\\\cosmo\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\","server":"","timeout":15000}'
}
````

And then it crashes with the same error as in the first post above.

**Comment by toddtarsi** [comment]
@cosmo0 - Lol sorry it took me a bit to respond, my kid hit the delete key on my email and I got lost trying to find this thread. Yeah I know it all sucks lol, I wrote it. You seem like you're pretty good at stuff. I bootstrap these options here:

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-runner/src/bin.ts

If you see any smoking guns, please let me know 🙂

**Comment by cosmo0** [comment]
Ok so it's the result of `selenium-manager.exe` returning multiple lines.

![image](https://user-images.githubusercontent.com/3973850/223673837-c536a4f1-e3c9-41f5-a824-2d0b13afaf48.png)

It works if, at `selenium-webdriver\common\seleniumManager.js`, method `driverLocation`, you change the return with:

````js
  let runners = result.replace('INFO\t', '').trim().split('\n');
  return runners[runners.length - 1].trim()
````

But it's very hacky and ugly, it assumes the last entry found will be the right one: it might work on Windows but probably won't on Linux/MacOS.

Using `fs.accessSync` I tried to determine if the file was an executable, but it seems Windows will gladly execute any random file, and `fs.accessSync('some jpg file', fs.constants.X_OK)` will not throw.

Sounds like the only clean way of fixing it is to fix `selenium-manager`. I'm looking at it but since I don't know Rust, I'm not sure if I'll be able to find the source of the problem.

**Comment by cosmo0** [comment]
I've opened a bug to fix selenium-manager, but in case the fix still returns multiple lines, I'm keeping this issue opened.

**Comment by toddtarsi** [comment]
Holy cow dude, I was right. You are pretty good at this. Nice troubleshooting and following it down to the boundaries. For now, I'm happy to write something a bit more silly as a hack. There's still lots of other questions on my end that I'd like to be sure of.

1. You're not seeing anything provided by your .side.yml file applied to the configuration?
2. When looking for the driver executable, should I check for `require.resolve('xyzdriver')` and specify that as the binary if nothing else more granular has been supplied before letting selenium-webdriver figure itself out or similar?

**Comment by cosmo0** [comment]
During debug I can see that it reads the `.side.yml`. It just seems to ignore the values if it finds a `chromedriver` on the PATH.

To me it looks like this is the culprit: https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chromium.js#L679-L702

I'm not sure what it's supposed to do, but I can see that the `.side.yml` values are passed in the `caps` parameter, but they are not used before `this.getDefaultService` is called, which in turns calls https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chrome.js#L263-L265 and then the constructor https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chrome.js#L160 ; you can see the constructor would gladly accept options but they are not passed, and `locateSynchronously` is the method calling `selenium-manager`.

![image](https://user-images.githubusercontent.com/3973850/223754511-798fc020-0979-4461-93c1-84b35c8e283f.png)

Maybe it's just a matter of passing the `caps` parameter to the `getDefaultService` method and other down the line?

**Comment by toddtarsi** [comment]
@cosmo0 - That sounds like a great theory. I'm sure you've already debugged through it, but this line here is the only place we instantiate drivers (in both the IDE and side-runner):

https://github.com/SeleniumHQ/selenium-ide/blob/640c2dfeb42dfc434a3b863aa86c79f09f636481/packages/side-runtime/src/webdriver.ts#L196

If you see any way to change the build steps here slightly to properly wind those parameters through, we can clear this bug. Thanks for deep-diving this code so well!
