### ISSUE TITLE
Selenium Side Runner - Indescript Web Driver error 

### ISSUE THREAD

**Issue by owainow** [SeleniumHQ/selenium-ide#1691]
## 🐛 Bug Report

I am running into a problem with Selenium Side Runner when trying to execute a set of tests. I am new to Selenium however I cannot find any examples of this error or resolution online. I have so far followed this sample demo [https://github.com/Azure-Samples/selenium-grid-aks-keda](https://github.com/Azure-Samples/selenium-grid-aks-keda.)  When I get to the end and try to run either the basic test suite or the app specific test suite I encounter an issue where I am unable to due to the below error:

```
info: Running test VoteCatAssert
debug: Playing state changed prep for test VoteCatAssert
info: Building driver for chrome
 FAIL  ../usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js
  Running project voteapp
    ✕ Running test VoteCatAssert (45 ms)

  ● Running project voteapp › Running test VoteCatAssert

    WebDriverError:

      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:618:11)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.03 s
Ran all test suites within paths "/usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js".
```

This error does not really provide me too much information. I am unsure why my web drivers are encountering this error both with the [basic test suite](https://github.com/Azure-Samples/selenium-grid-aks-keda/tree/main/testsuites/basic)  and [app test suite](https://github.com/Azure-Samples/selenium-grid-aks-keda/tree/main/testsuites/azurevote) . This test is being triggered using the side runner. I have tried installing the npm package for selenium-webdrivers. I have also tried this on multiple instances. I am using an AKS cluster as my backend if it makes any odds. Any help would be much appreciated.  

## To Reproduce

Steps to reproduce the behaviour:

Deploy the above demo. 

## Expected behaviour

I would expect when triggering my selenium tests with the side-runner for my tests to execute or at least a detailed error message in the event they went wrong. 

## Project file reproducing this issue (highly encouraged)

All config and files can be found in the repo linked above.

Issues without a reproduction project are likely to stall.

## Environment

OS: Ubuntu 20
Selenium SIDE Runner Version:  4.0.0-alpha.55
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node Version: 18.13.0
Only required if using selenium-side-runner
-->

**Comment by toddtarsi** [comment]
Oh man, that error really sucks. Try adding these two flags `-dD` and see if they give you any info. If that doesn't work, we might be able to get more info using environment variables like `NODE_DEBUG=webdriver` or similar. Sorry! 😬

**Comment by owainow** [comment]
Hi, just to update. I believe the issue that was causing this was the port I was calling. As I was testing using Grid deployed in AKS the ingress port exposed was 80 not 4444. This was terrible to diagnose as the side runner makes it look like the cause is a module issue based on the error output. Despite having the error code e.g 401 in this case it is not displayed in the error output. I will add the error code to the http.js file at some point and make a pull request. Cheers.

**Comment by toddtarsi** [comment]
@owainow - Holy cow, that would be amazing. Thank you for explaining the issue and planning to contribute back. I'm sorry for all of the pain around this error and I look forward very excitedly to your PR. Thank you!
