### ISSUE TITLE
Build the app with electron-builder

### ISSUE THREAD

**Issue by Mykab54** [SeleniumHQ/selenium-ide#1693]
I try to build the app with electron-builder. For this, I have added in package.json the following:
```
"build": {
    "appId": "AppID",
    "productName": "seleniumIDE",
    "directories": {
      "output": "dist"
    },
    "linux": {
      "target": [
        {
          "target": "deb"
        }
      ],
   }
}
```
And in scripts:
```
"scripts": {
    "dist": "electron-builder"
}
```
After that I do 
```
$ pnpm run dist
```
It works but when I want to start the app with
```
$ seleniumIDE
```
I got this error:
"
Unable to startup due to chromedriver error: Missing executable at path /opt/seleniumIDE/resources/app.asar.unpacked/packages/-selenium-ide/node_modules/electron-chromedriver/bin/chromedriver
"

**Comment by toddtarsi** [comment]
@Mykab54 - You adding this to the top level package.json or the package.json in the selenium-ide package?

**Comment by Mykab54** [comment]
@toddtarsi I add this in the root of the project folder

**Comment by toddtarsi** [comment]
Check out packages/selenium-ide/package.json. The build:electron command in there is used by the CI to build for mac / windows / etc

**Comment by toddtarsi** [comment]
@Mykab54 - Just wanted to check in and see if you were able to build successfully

**Comment by Mykab54** [comment]
I tried on Linux and windows and it didn't work. I got the following error on windows:
```
@seleniumhq/selenium-ide@4.0.0-alpha.47 build:electron D:\Proj\src\selenium-ide\packages\selenium-ide
CSC_IDENTITY_AUTO_DISCOVERY=false electron-builder -mwl -c.electronVersion $(node -e "console.log(require('electron/package.json').version)") --publish never

'CSC_IDENTITY_AUTO_DISCOVERY' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "build:electron" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by Mykab54** [comment]
@toddtarsi  I recloned selenium-ide and tried to build with electron-builder from packages/selenium-ide. I got the following:
```
> @seleniumhq/selenium-ide@4.0.0-alpha.47 build:electron /home/gsw/Desktop/ide/selenium-ide/packages/selenium-ide
> CSC_IDENTITY_AUTO_DISCOVERY=false electron-builder -mwl -c.electronVersion $(node -e "console.log(require('electron/package.json').version)") --publish never

  • electron-builder  version=24.4.0 os=5.15.0-79-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  ⨯ /home/gsw/Desktop/ide/selenium-ide/node_modules/.pnpm/iconv-corefoundation@1.1.7/node_modules/iconv-corefoundation/lib/native.node: invalid ELF header  failedTask=build stackTrace=Error: /home/gsw/Desktop/ide/selenium-ide/node_modules/.pnpm/iconv-corefoundation@1.1.7/node_modules/iconv-corefoundation/lib/native.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/gsw/Desktop/ide/selenium-ide/node_modules/.pnpm/iconv-corefoundation@1.1.7/node_modules/iconv-corefoundation/lib/native.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/gsw/Desktop/ide/selenium-ide/node_modules/.pnpm/iconv-corefoundation@1.1.7/node_modules/iconv-corefoundation/lib/index.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "build:electron" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by toddtarsi** [comment]
@Mykab54 - To give some context, that -mwl flag means -mac -windows -linux. I think you just want linux here, try replacing `-mwl` with just `-l`. That said, elf header sounds kinda linux-y, but that might make this less painful to debug

**Comment by toddtarsi** [comment]
@Mykab54 - I am going to close this issue. Our CI builds for all three platforms pretty consistently, so if there is a knowledge gap I can close, I'd be happy to. But all and all, there's not much else for me to do here.
