### ISSUE TITLE
Unknown command storeXpathCount in selenium-side-runner

### ISSUE THREAD

**Issue by pabloneruda1** [SeleniumHQ/selenium-ide#1698]
Missing command "storeXpathCount" in selenium-side-runner

log:
    Unknown command storeXpathCount

      at WebDriverExecutor.name (node_modules/@seleniumhq/side-runtime/src/webdriver.ts:229:13)
      at CommandNode._executeCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:120:51)
      at CommandNode.execute (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:100:31)
      at Playback._executeCommand (node_modules/@seleniumhq/side-runtime/src/playback.ts:559:22)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:436:18)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:493:14)
      at node_modules/@seleniumhq/side-runtime/src/playback.ts:345:9

**Comment by toddtarsi** [comment]
Yes! That command no longer exists in v4!

If you're still on v3, you might want to stick to a v3 version of the side-runner.

If you'd like to come up to v4, this migration tool should automatically upgrade your side files. :)

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-migrate/README.md
