### ISSUE TITLE
Error in side-runner at the close command 

### ISSUE THREAD

**Issue by fmrahman** [SeleniumHQ/selenium-ide#1806]
## 💥 Regression Report

The side command having a close command is throwing the below error.

```
WebDriverError: disconnected: not connected to DevTools
      (failed to check if window was closed: disconnected: not connected to DevTools)
      (Session info: chrome=120.0.6099.224) during close::

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:513:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:740:17)
      at WebDriverExecutor.doClose (node_modules/@seleniumhq/side-runtime/src/webdriver.ts:398:5)
      at CommandNode._executeCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:152:18)
      at CommandNode.execute (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:112:20)
      at Playback._executeCommand (node_modules/@seleniumhq/side-runtime/src/playback.ts:560:22)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:438:18)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at Playback._executionLoop (node_modules/@seleniumhq/side-runtime/src/playback.ts:495:14)
      at node_modules/@seleniumhq/side-runtime/src/playback.ts:346:9
```

## Last working version

Worked up to version: 3.17.0

Stopped working in version: 4.2.0

## To Reproduce

Steps to reproduce the behavior: keep the close command in the script

## Expected behavior

The error should not come with the close command.

## Project file reproducing this issue (highly encouraged)

any side script which has close command

{
      "id": "7a240559-dc46-414c-9b8b-4341476a2351",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }

## Environment

OS: Oracle Linux 7
Selenium IDE Version: 
Selenium SIDE Runner Version:  4.0.2
Nodejs version used is v16.13.1

Browser: Chrome 
Browser Version: 120.0.6099.224 (64-bit)

**Comment by toddtarsi** [comment]
Appears to run fine on my machine. I think you've got something wrong in your system setup:

https://stackoverflow.com/questions/59847431/org-openqa-selenium-webdriverexception-disconnected-not-connected-to-devtools
