### ISSUE TITLE
jest timeout option not working in selenium side runner ver 4.0.12

### ISSUE THREAD

**Issue by NikhilHedau** [SeleniumHQ/selenium-ide#1860]
## 🐛 Bug Report

--jest-timeout option is not working with selenium side runner ver 4.0.12. The tests are running even when the timeout has occurred.
Output file. [console-output.txt](https://github.com/user-attachments/files/17027692/console-output.txt)

I see this behaviour even when some commands are failing . Instead of the test failing the test continues to run. 
PFA below output.

> console.warn
>     Unexpected error occured during command: click-id=customer-email- retrying...
> 
>       at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:234:15)
>       at node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:197:18
> 
>   console.error
>     element click intercepted: Element <input class="input-text" type="email" data-bind="
>                                 textInput: email,
>                                 hasFocus: emailFocused" name="username" data-validate="{required:true, 'validate-email':true}" id="customer-email"> is not clickable at point (572, 343). Other element would receive the click: <div id="checkout-loader" data-role="checkout-loader" class="loading-mask">...</div>
>       (Session info: chrome=128.0.6613.138)
> 
>       at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:240:17)
>       at node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:197:18

## To Reproduce
selenium-side-runner script.side  -c "browserName=chrome" -o ~/Documents/test-data --debug --debug-startup --timeout 30000 --jest-timeout 10000

## Expected behavior
The test should fail when the timeout has occurred.

## Project file reproducing this issue (highly encouraged)

Side File . [luma-mpa.txt](https://github.com/user-attachments/files/17027614/luma-mpa.txt)

## Environment

OS:  Mac OS Sonoma 14.5
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version:  4.0.12
Node version: 20.11.1
Browser: Google Chrome
Browser Version: 128.0.6613.138
Chromedriver Version: 128.0.6613.84

**Comment by NikhilHedau** [comment]
Hi @toddtarsi , 
Can you please check?
