### ISSUE TITLE
WebDriverError: No active session with ID

### ISSUE THREAD

**Issue by tiagobrito** [SeleniumHQ/selenium-ide#249]
## Meta -
OS:  OSX
Selenium IDE Version:  v3.1.0-beta.5
Browser:  Chrome

## Expected Behavior -
Replay the test recorded in the .side file using the remote webdriver (e.g. Browserstack).

## Actual Behavior -
Throws an exception.

## Steps to reproduce -
I'm recording a test case with selenium ide 3.1.0-beta.5 and using selenium-runner-side to replay the tests saved in the .side file. Using Browserstack as a remote webdriver it gives the following error:

```bash
selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

WebDriverError: No active session with ID 5e9457adaf7e72615d540a8dc543a890382927e8
    at Object.checkLegacyResponse (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.findElements(By(css selector, h1.fold__heading))
    at WebDriver.schedule (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebDriver.findElements (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:1048:19)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/until.js:243:23
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:938:14
    at TaskQueue.execute_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: <anonymous>
    at pollCondition (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2195:19)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2191:7
    at new ManagedPromise (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2190:22
    at TaskQueue.execute_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: Waiting for element to be located By(css selector, h1.fold__heading)
    at scheduleWait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at WebDriver.wait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at Object.it (/Users/brito/Sites/selenium-browserstack-demo/side-suite-Untitled Project/Default Suite.test.js:7:12)
    at Object.asyncFn (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
    at resolve (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
    at new Promise (<anonymous>)
    at mapper (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
    at promise.then (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by corevo** [comment]
Let me know if [beta 7](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.1.0-beta.7) works for you.

**Comment by tiagobrito** [comment]
@corevo Thanks, it seems that the beta 7 fixed the problem.
I just notice one thing, that is if the element doesn't exist Browserstack will keep trying to find the element instead of giving an assert error.
![screen shot 2018-06-18 at 09 52 35](https://user-images.githubusercontent.com/1071148/41526966-a25ed10c-72dd-11e8-8b23-2b372b4d9b70.png)
The test terminates after a while with a session timeout.

**Comment by corevo** [comment]
The screenshot is interesting, unsure if it's a problem with the test, the runner or browserstack, I'll need more information.  
Perhaps it's dying on `driver.wait`?

**Comment by tiagobrito** [comment]
After a while the tests breaks with:

```bash
/Default Suite.test.js
/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

WebDriverError: Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '185-44-130-223', ip: '185.44.130.223', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.findElements(By(css selector, *[id="becomeLandlord"]))
    at mixin.schedule (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at mixin.findElements (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:1048:19)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/until.js:243:23
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:938:14
    at TaskQueue.execute_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:668:7
From: Task: <anonymous>
    at Timeout.pollCondition [as _onTimeout] (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2195:19)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
From: Task: Waiting for element to be located By(css selector, *[id="MyIdThatDoesntExists"])
    at scheduleWait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at mixin.wait (/Users/brito/Sites/selenium-browserstack-demo/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at Object.it (/Users/brito/Sites/selenium-browserstack-demo/side-suite-Untitled Project/Default Suite.test.js:23:12)
    at Object.asyncFn (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
    at resolve (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
    at new Promise (<anonymous>)
    at mapper (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
    at promise.then (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by corevo** [comment]
I see, I need to tone down the implicit wait times, it reaches timeouts.

**Comment by anilreddii** [comment]
Hello,
Facing the below issue when am running my test suite on TFS, but locally dont see any error.

WebDriverError: No active session with ID 4f54805f9d7fbf34dba27065eba93f71
Failed: No active session with ID 4f54805f9d7fbf34dba27065eba93f71

could some one please help me out how can i resolve the issue ? Please let me know if any information is required

**Comment by ashwinvellore** [comment]
I am facing this issue in webdriverio when running the chrome browser on headless mode.
I had updated chrome before i started seeing this issue.

[12:10:56]      Failed to take screenshot on reject:     {"message":"No active session with ID 32b83d1dfd3a621265f1198d48da2f0d","type":"RuntimeError","seleniumStack":{"type":"NoSuchDriver","message":"A session is either terminated or not started","orgStatusMessage":"No active session with ID 32b83d1dfd3a621265f1198d48da2f0d"}}
No active session with ID 32b83d1dfd3a621265f1198d48da2f0d
ERROR: No active session with ID 32b83d1dfd3a621265f1198d48da2f0d
