### ISSUE TITLE
How to run .side files with selenium-side-runner in different browsers?

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#327]
## 💬 Questions and Help

Running .side files with selenium-side-runner in chrome (chromediver) workes perfectly, but I am wondering how to run the test files with different browsers, like safari? I have downloaded the `selenium-safari-driver-2.43.1`, but I am unable to make it work with the selenium-side-runner. 
What is the correct way to do this?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
Make sure you have `safaridriver` in `PATH`.  
And run `selenium-side-runner -c "browserName=safari"`.

**Comment by cemol** [comment]
I using Windows, how do i download the correct verion of safari? I am getting this error:

**Comment by cemol** [comment]
Thanks! :)
But I'm using Windows, how do i download the correct verion of safari? I'm getting this error:

```
FAIL ./project.test.js
  ● Test suite failed to run

    The safaridriver executable could not be found on the current PATH.
          Please ensure you are using Safari 10.0 or above.

      at findSafariDriver (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/safari.js:44:11)
      at new ServiceBuilder (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/safari.js:64:22)
      at Function.createSession (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/safari.js:249:19)
      at createDriver (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:660:16)
      at buildDriver (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.324s, estimated 13s
Ran all test suites.

```

**Comment by corevo** [comment]
Safari 10 is only available on macOS.

**Comment by cemol** [comment]
ok, thanks, then i will try to downloade it on linux!

**Comment by corevo** [comment]
Only mac, Apple discontinued development of safari on all OS except macOS.  
Also I am locking this issue, because it has nothing to do with the runner, it is a problem with installing safari driver.
