### ISSUE TITLE
selenium-side-runner project wildcard not working

### ISSUE THREAD

**Issue by CharlJKruger** [SeleniumHQ/selenium-ide#345]
## 🐛 Bug Report

When running `selenium-side-runner *.side` as per the README.md, it cannot find/match any files

## To Reproduce
run `selenium-side-runner *.side`

## Expected behavior

match all *.side files and execute them

**Comment by corevo** [comment]
We use that right [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/package.json#L16), every build.  
Would you mind me asking what shell are you using, and in which directory are they, if you glob them inside a nested directory you might wanna try using `selenium-side-runner directory-containing-files/*.side`.

**Comment by CharlJKruger** [comment]
I created a repo to reproduce it https://github.com/CharlJKruger/selenium
run `npm install` and then `npm run test`

Please note I cleared out the `.side.yml` so you will have to add your own config.

There is a `projects` dir with two test .side files within it.

Running on a win 10 machine via normal cmd and git bash

```
selenium-side-runner projects/*.side

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\_io2.0\test\selenium\projects\*.side'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at _commander2.default.args.map.p (C:\_io2.0\test\selenium\node_modules\selenium-side-runner\dist\index.js:240:76)
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\_io2.0\test\selenium\node_modules\selenium-side-runner\dist\index.js:240:43)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! selenium@1.0.0 test: `selenium-side-runner projects/*.side`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the selenium@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-08-15T18_29_44_383Z-debug.log
```
