### ISSUE TITLE
Selenium Side Runner and Internet Explorer on Windows 8

### ISSUE THREAD

**Issue by johnsharp5775** [SeleniumHQ/selenium-ide#492]
## System
OS: Windows 8.1
Driver: IEDriverServer.exe
CMD line: selenium-side-runner "Test.side" -c "browserName=ie"

## Execpted:
I'm expecting the tests to run or at least have Internet Explorer appear to do something. The behaviour received is that the test file is opened and after about 2 seconds a message similar to _ECONNREFUSED connect ECONNREFUSED 127.0.0.1:8903_ appears.

The error messages that are showing don't help to resolve the issue myself.

### Stack trace:
      at ClientRequest.<anonymous> (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/http/index.js:238:15)
      From: Task: WebDriver.createSession()
      at Function.createSession (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/ie.js:423:41)
      at createDriver (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:648:16)
      at buildDriver (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.
js:32:32)

**Comment by capoerafreak** [comment]
according to my Information selenium ide doesn‘t support IE by now ...

**Comment by tourdedave** [comment]
Confirmed similar behavior with version 3.4.2 of the runner on Windows 8, IE 11, using Node 10, and version 3.141 of IEDriverServer.exe (32-bit).

Two windows get spawned and one closes. In the first window the test attempted to execute commands and completed `open`. The second window attempted a connection to localhost and once it closed the test errored out with a `NoSuchWindowError`.

**Comment by johnsharp5775** [comment]
Hi Dave, yes, that's the main page I've been using for all of the information about getting IE to work so far. I've just tried this too: selenium-side-runner "tests/Test.side" -c "browserName=ie" --log-level="TRACE" --log-file=results.txt

It's producing this:
info:    Running tests/Test.side
FAIL ./Default Suite.test.js
  ● Test suite failed to run

    ECONNREFUSED connect ECONNREFUSED 127.0.0.1:30691

      at ClientRequest.<anonymous> (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/http/index.js:238:15)
      From: Task: WebDriver.createSession()
      at Function.createSession (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/ie.js:423:41)
      at createDriver (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:648:16)
      at buildDriver (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (C:/Users/developer/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.324s
Ran all test suites.

But there's no results.txt file as far as I can see....?

Cheers for looking too.

John

**Comment by capoerafreak** [comment]
@tourdedave: we are at the selenium IDR Github-Page and the ReadMe: https://github.com/SeleniumHQ/selenium-ide/blob/master/README.md

**Comment by tourdedave** [comment]
@capoerafreak If you're referring to where the IDE can be used, then yes, IE is not supported. This issue has to do with the command-line runner which takes a Selenium IDE project (e.g., a suite of tests) and runs it on any of the officially supported browser/operating system combinations in Selenium (which means in this case, IE *is* supported). You can see the readme for it here: https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-side-runner

**Comment by tourdedave** [comment]
You're welcome!

**Comment by johnsharp5775** [comment]
Thanks - I'll have another try. I'll set up a clean VM and give it a bash on that.

**Comment by tourdedave** [comment]
Sounds good, thanks!

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
