### ISSUE TITLE
Error: "Test suite failed to run. The ChromeDriver could not be found on the current PATH."

### ISSUE THREAD

**Issue by elijahtlang** [SeleniumHQ/selenium-ide#590]
🐛 Bug Report

Just created and saved my first .side, downloaded node.js, downloaded selenium-side-runner, and installed siderunner and chromedriver. In CMD, ran selenium-side-runner [path to side], and got the following output:

```
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.

      at new ServiceBuilder (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:232:13)
      at getDefaultService (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:321:22)
      at Function.createSession (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:696:44)
      at createDriver (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:155:33)
      at Builder.build (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:647:16)
      at buildDriver (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:65:17)
      at WebdriverEnvironment.setup (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:36:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.411s
Ran all test suites.
```
Not sure exactly why I'm getting this error. Chromedriver appears to install successfully, and it appears in the folders indicated in the output.

OS: Windows 10 Home v17763
Selenium IDE Version:  3.5.8 (firefox add-on)
Selenium SIDE Runner Version:  3.5.9
Node version: 10.15.1
Browser: Chrome
Browser Version: 72.0.3626.119 (64-bit)

**Comment by corevo** [comment]
Make sure that `chromedriver` is in [PATH](https://www.java.com/en/download/help/path.xml)

**Comment by elijahtlang** [comment]
That helped fix that error, thank you.
