### ISSUE TITLE
Runner Download firefox automatically

### ISSUE THREAD

**Issue by tatototino** [SeleniumHQ/selenium-ide#632]
## 🚀 Feature Proposal

I´m running selenium-side-runner script to download a file using firefox/gecko  and I´ve searched and I didn´t found anything about to do it automatically ( np pop-up to ask file download location in firefox)

It will be great if has the feacture to firefox download the file automatically.

Regards,

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by tourdedave** [comment]
This use case isn't supported on the current platform. But as we move to Electron, we're looking into ways to potentially support this functionality.

**Comment by tatototino** [comment]
Do you know any work around to pass to firefox prefs like "browser.helperApps.neverAsk.saveToDisk" selenium-side-runer to download it automatically?

**Comment by tourdedave** [comment]
It might be possible through the `moz:FirefoxOptions` capability in geckodriver ([link](https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#moz-firefoxoptions)). You can specify these like any other capability in the runner (e.g., with the `-c` flag). You can see an example of this for Chrome [here](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#chrome-specific-capabilities).

**Comment by zewa666** [comment]
Sry for hijacking this issue @tourdedave but could you explain a bit about the plans of moving to Electron? Is that specifically for the side-runner? There are a few things to keep in mind when doing so for a CLI, namely Electron requires an xserver to execute which could be a chore in CI environments.

**Comment by tatototino** [comment]
Hi tordedave,

Thank you for your answer, but I had a issue closed about a issue about to get it works.

When a set up any moz:FirefoxOptions I get error, I think the selenium-webdriver can´´t handle moz:firefoxOption in the capabilities section because it contains ":" in the json object:

when I pass any value in moz:firefoxOption I get the same error:

  at Object.throwDecodedError (../../node_modules/selenium-webdriver/lib/error.js:550:15)
  at parseHttpResponse (../../node_modules/selenium-webdriver/lib/http.js:545:13)
  at Executor.execute (../../node_modules/selenium-webdriver/lib/http.js:468:26)

Response {
status: 500,
body: '{"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}',

Maybe It happen because http.js can't parse when a object json contain colon like "moz:firefoxOption", you can reproduce using -c from side-runner or edit the package.json directly in side-suite dir.

Regards,

**Comment by tatototino** [comment]
About side runner command I´m getting the following error:

selenium-side-runner -c "browserName=firefox moz:firefoxOptions.prefs={"browser.helperApps.neverAsk.saveToDisk":true}"  file.side
info:    Running /home/totino/totvssuporte.zendesk.com(3).side
 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    InvalidArgumentError: prefs value is not an object

      at Object.throwDecodedError (../../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../node_modules/selenium-webdriver/lib/http.js:545:13)
      at Executor.execute (../../node_modules/selenium-webdriver/lib/http.js:468:26)

Command { name_: 'getStatus', parameters_: {} }
Response {
  status: 200,
  body: '{"value":{"message":"","ready":true}}',
  headers:
   Map {
     'content-type' => 'application/json; charset=utf-8',
     'cache-control' => 'no-cache',
     'content-length' => '37',
     'date' => 'Wed, 27 Mar 2019 23:26:17 GMT' } }
{ message: '', ready: true }
Command {
  name_: 'newSession',
  parameters_:
   { desiredCapabilities: { browserName: 'firefox', 'moz:firefoxOptions': [Object] },
     capabilities: { alwaysMatch: [Object] } } }
Response {
  status: 400,
  body: '{"value":{"error":"invalid argument","message":"prefs value is not an object","stacktrace":""}}',
  headers:
   Map {
     'content-type' => 'application/json; charset=utf-8',
     'cache-control' => 'no-cache',
     'content-length' => '95',
     'date' => 'Wed, 27 Mar 2019 23:26:17 GMT' } }
{ error: 'invalid argument',
  message: 'prefs value is not an object',
  stacktrace: '' }
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.271s
Ran all test suites.
