### ISSUE TITLE
Target browser undefined error even though the target browser is defined

### ISSUE THREAD

**Issue by kdunckley** [SeleniumHQ/selenium-ide#640]
## 🐛 Bug Report

Hello - I am trying to run the following Groovy script:

command = "/usr/local/bin/selenium-side-runner -c 'browserName=chrome chromeOptions.args=[disable-infobars, headless]' /home/ubuntu/LM-SNMP-Troubleshooting-page-load.side"

Process process = command.execute()
def out = new StringBuffer()
def err = new StringBuffer()
process.consumeProcessOutput( out, err )
process.waitFor()
if( out.size() > 0 ) println out
if( err.size() > 0 ) println err

I am getting this output:
[32minfo [39m: Running /home/ubuntu/LM-SNMP-Troubleshooting-page-load.side 
FAIL ./DefaultSuite.test.js 
● Test suite failed to run 
TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()? 
at Builder.build (../../../../lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:574:13) 
at buildDriver (../../../../lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:65:17) 
at WebdriverEnvironment.setup (../../../../lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:36:32) 
Test Suites: 1 failed, 1 total 
Tests: 0 total 
Snapshots: 0 total 
Time: 0.173s 
Ran all test suites. 

When I run the command directly from the CLI, it runs as expected:

ubuntu@ip-172-31-8-108:~$ /usr/local/bin/selenium-side-runner -c 'browserName=chrome chromeOptions.args=[disable-infobars, headless]' /home/ubuntu/*.sideinfo:    Running /home/ubuntu/LM-SNMP-Troubleshooting-page-load.side
 PASS  ./DefaultSuite.test.js (10.799s)
  Default Suite
    ✓ find-and-load-SNMP-Troubleshooting-page (7731ms)

[LM-SNMP-Troubleshooting-page-load.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/3035713/LM-SNMP-Troubleshooting-page-load.side.txt)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        11.095s
Ran all test suites.

Why does it think that my target browser is undefined when I have browserName=chrome in the command?

Thanks,
Kellena

## Environment

OS: Ubuntu
Selenium IDE Version:  3.5.8
Selenium SIDE Runner Version:  3.5.11
Node version: 8.10.0
Browser: Chrome
Browser Version: 73.0.3683.86

**Comment by kdunckley** [comment]
After further troubleshooting, I believe this is a groovy execute() issue rather than a selenium-side-runner issue.
