### ISSUE TITLE
selenium ide tests fail through terminal

### ISSUE THREAD

**Issue by jonesp100** [SeleniumHQ/selenium-ide#643]
Hi,

Using cmd line runner for the first time - consistently fails but runs fine via IDE 

Example issue below;  getting varying issues but mostly it looks like elements can't be found 

TimeoutError: Waiting for element to be located By(css selector, *[name="months"])
    Wait timed out after 15004ms

**Comment by Loborg** [comment]
I have the same issue mainly whit the select command. In the IDE it runns perfectly but in the side runner it can not find the selector.
Here is the .side code snipet:
https://gist.github.com/Loborg/f766400519b9f511121756c3d2c9b8a6

And the error log:

 FAIL  ./debug.test.js (8.623s)
  debug
    × test_88 (3066ms)

  ● debug › test_88

    WebDriverError: element not interactable
      (Session info: chrome=73.0.3683.86)
      (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

      at Object.checkLegacyResponse (../../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:585:15)
      at parseHttpResponse (../../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:533:13)
      at Executor.execute (../../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        8.892s, estimated 16s
Ran all test suites.

**Comment by vtran1235** [comment]
I'm also getting the same issue as Loborg stated above

**Comment by fn-marc-clinedinst** [comment]
I have also been able to reproduce this issue. In my case, it happens during a page transition during a login script. After clicking on the "login" button on our landing page, a page transition occurs and the script immediately fails with the following error input:

`selenium-side-runner FiscalNote.side --server http://localhost:4444/wd/hub -c "browserName=chrome" 
info:    Running FiscalNote.side
 FAIL  ./DefaultSuite.test.js (10.477s)
  Default Suite
    ✕ login (8071ms)

  ● Default Suite › login

    NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".auth0-lock-input-email input"}
      (Session info: chrome=72.0.3626.81)
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.9.125-linuxkit x86_64)

      at Object.checkLegacyResponse (../../../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:585:15)
      at parseHttpResponse (../../../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:533:13)
      at Executor.execute (../../../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.74s
Ran all test suites.
`

The script runs without issue when executed through Selenium IDE but fails when executed through the command-line runner. 

To be a bit more specific, the failure occurs during a transition from our landing page to our actual login page. I was able to work around it by inserting a hard-coded pause of a few seconds instead of relying on the `wait for element visible` command.

**Comment by tourdedave** [comment]
Thanks for the info, all!

@Loborg Can you please provide a valid SIDE project file for me to review?

**Comment by Loborg** [comment]
See my attachment enclosed.

[select_issue.zip](https://github.com/SeleniumHQ/selenium-ide/files/3176757/select_issue.zip)

**Comment by tourdedave** [comment]
Thanks @Loborg!

**Comment by shansb-dev** [comment]
I also get these ```WebDriverError: element not interactable``` exceptions, in case elements are targeted that are not yet present. 

My workarround is sth like this:
```
execute script | return(150) | delay
pause | vars.delay
```
But it is very tedious to figure out all locations for these needed synchronizations because there is no error msg that indicates the problematic line in the ide.
```
WebDriverError: element not interactable
      (Session info: headless chrome=74.0.3729.157)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-148-generic x86_64)
```

It seems like the implicit wait that works fantastically in the selenium ide plugin does not work for the selenium-side-runner.

**Comment by tourdedave** [comment]
Explicit waits are used in the emitted code for the runner. The condition that's being used can be improved, but there might still be issues which due to the fact that the IDE and the runner are currently using two different execution methods.

Put another way, I can fix the immediate issue, but there will possibly be others which will be blocked until we move the IDE to a native app which uses playback on WebDriver.

**Comment by dillonz** [comment]
I am getting messages when trying to run a waitForElementVisible command, where it works great in the IDE, but not in the side runner.  It seems that it doesn't wait the amount of time I set in the command line.  In other words, the last requests finishes and immediately the test fails, giving me this error 

> NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".breadcrumb-text"}
>       (Session info: chrome=75.0.3770.100)

 instead of waiting the 5 seconds for it to be visible that I set in the IDE.

**Comment by nexocentric** [comment]
Any updates on this issue?

**Comment by nexocentric** [comment]
So, I seem to be have the same issue as @dillonz . Even though I'm using wait functions, the selenium-side-runner program seems to ignore the wait and automatically fail the test when it can't find an element.

Placing pauses between commands has remedied the issue, but this is most definitely not the ideal way to solve this issue.

Any comments as to why this is happening or methods for remedying the issue aside from hard pauses?

Thanks for your help and support. If you need any log information, just let me know.

**Comment by tourdedave** [comment]
The near-term fix to address the `NoSuchElementError` would be to add a run-time flag to the runner which would make it emit `wait for element visible` checks before trying to interact with each element. By default `wait for element present` checks are emitted before attempting to interact with each element instead. We don't use visible checks in the runner because 1) a rudimentary element present checks handle most common cases pretty well and 2) there is an order of magnitude difference in performance between these two checks in Selenium. Making this change automatic would add a non-trivial amount of time to every user's test runs. But making it something users can opt-in to is a reasonable compromise.

**Comment by amenk** [comment]
I think it would be very helpful and important to have a way that Selenium IDE and side-runner work consistently.

**Comment by tourdedave** [comment]
@amenk I agree. It's a fundamental problem that needs to be addressed that is not simple or easy. You can learn more about why that is and the direction we're thinking of taking [here](https://groups.google.com/d/msg/selenium-developers/vzN6O259pQQ/Rt2ZkMTeBwAJ) (if you're interested).

**Comment by devnull-0** [comment]
I would love to see this enhancement! 
Thanks a million guys for your work on the code. I'd love to contribute - but I'm just an ops guys using the runner for monitoring  :-)

**Comment by amenk** [comment]
Thanks for your infos @tourdedave and of course for the work on the project :)

Our workflow would be to record tests with selenium IDE and use side-runner for monitoring purpose. Right now we have to drop lots of wait to the code - it's working, but annoying. 

1. Is there another way to automatically execute the .side files, in the same way like the IDE does it?
2. is there any very rough timing for the fundamental problem to be solved or any way we could support?

**Comment by jackrabbithanna** [comment]
+1 for something to make "wait for element visible" or other "wait" commands to work. 
Without this, it is almost useless, so many sites have ajax/javascript that require use of these commands.

**Comment by rvega** [comment]
+1  I just spent a lot of time authoring tests in the IDE to later find out they won't work in the side-runner. 
Note: at some point during November 2020 my tests were running fine in both the IDE and the side-runner.

**Comment by slovatt** [comment]
I'm getting the same issue the first time I run any of my Selenium IDE test suites in the command line.

When the same test is executed a second time, without any changes, it runs successfully.

`ElementNotInteractableError: element not interactable`
`      (Session info: headless chrome=85.0.4183.121)`

`      at Object.throwDecodedError (../../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)`
`      at parseHttpResponse (../../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)`
`      at Executor.execute (../../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)`
`      at Driver.execute (../../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:699:17)`

**Comment by pbrumby** [comment]
I'm getting the same issue as everyone else. The IDE works fine but the cmd line runner runs into issues eg. 

> ElementNotInteractableError: element not interactable
      (Session info: chrome=92.0.4515.131)

**Comment by Bertie-Chapman** [comment]
Any progress on this?

**Comment by toddtarsi** [comment]
@Bertie-Chapman - You on v4?
