### ISSUE TITLE
The ChromeDriver could not be found on the current PATH

### ISSUE THREAD

**Issue by zeasghar** [SeleniumHQ/selenium-ide#664]
I have installed Chrome Driver using npm command npm install -g chromedriver. It got installed successfully. I have added that chrome driver in PATH environmental variable. But still getting below Error:

Environment Details:
Chrome version :Version 73.0.3683.103 (Official Build) (64-bit)
Chrome Driver Version: 74.0.3729.6
OS: Windows 10 Pro
Node Version: 10.15.3

Below Highlighted Path is added in Environmental Variables 
![Path Variable](https://user-images.githubusercontent.com/48723174/56898088-a4e50300-6aa9-11e9-894f-9035b26109c8.PNG)
![EnvironmentalVariable](https://user-images.githubusercontent.com/48723174/56898108-a7dff380-6aa9-11e9-8f7b-cb89ba1553a6.PNG)

 

The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.

      at new ServiceBuilder (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:232:13)
      at getDefaultService (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:321:22)
      at Function.createSession (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:696:44)
      at createDriver (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:155:33)
      at Builder.build (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:647:16)
      at buildDriver (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:65:17)
      at WebdriverEnvironment.setup (C:/Users/zeasghar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:36:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.207s
Ran all test suites.

**Comment by corevo** [comment]
What you added to PATH seems faulty, I'm not sure on windows but on mac it should end with `node_modules/.bin`

**Comment by corevo** [comment]
Also please use slack or irc this is an issue tracker for the IDE, you can use the irc to seek help on installing chromedriver.

**Comment by zeasghar** [comment]
Can you please share IRC and Slack details?

**Comment by corevo** [comment]
## 💬 Questions and Help

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
