### ISSUE TITLE
Unable to run selenium side runner via command prompt

### ISSUE THREAD

**Issue by ojake13** [SeleniumHQ/selenium-ide#712]
I'll start out by saying the web automation test I've created works perfectly using the selenium IDE web GUI -- the issue arises when I try to run the command via command prompt:

`selenium-side-runner -c "browserName=firefox" C:\path_to_side\sidefile.side`

At first, I was receiving this output:

`C:\Users\admin>selenium-side-runner -c "browserName=firefox" C:\Users\admin\Documents\VRA_scoring.side
info:    Running C:/Users/admin/Documents/VRA_scoring.side
 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    The geckodriver.exe executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/ and ensure it can be found on your PATH.

      at findGeckoDriver (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/firefox.js:427:11)
      at new ServiceBuilder (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/firefox.js:516:22)
      at Function.createSession (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/firefox.js:574:21)
      at createDriver (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:155:33)
      at Builder.build (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:655:16)
      at buildDriver (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:66:17)
      at WebdriverEnvironment.setup (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:37:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.235s
Ran all test suites.`

However, I believe that was due to the lack of a valid test suite. Once I added a proper test suite and purged/re-installed npm, this is the output that I am concerned about:

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\admin\Documents\node_modules\selenium-side-runner\dist\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

Why is this? I'm pretty sure I have installed all dependencies. I'm not sure how to get package.json, as I only see package-lock.json. Sorry I am a rookie using selenium, and really don't know much at all about the software.

**Comment by tourdedave** [comment]
`geckodriver` is a required dependency. It's how Selenium communicates with Firefox. You need to download it and add it to your system's path. Or you can download an npm package that handles this for you. See [the runner's documentation](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#installing-a-browser-driver) for details.

**Comment by ojake13** [comment]
I have downloaded both the npm package and gecko driver before posting this question. I am well aware of the web drivers necessary. Maybe it's in the wrong path? What exactly is the 'system Path'?

**Comment by ojake13** [comment]
If you read through you can clearly see the second output gives me no error regarding gecko driver....so obviously that wouldn't be the answer to the question.

**Comment by ojake13** [comment]
The current output I am now receiving is as follows:

`info:    Running C:/Users/admin/Documents/VRA_scoring.side
 FAIL  ./DefaultSuite.test.js (5.84s)
  Default Suite
    × VRAscores (2948ms)

  ● Default Suite › VRAscores

    InsecureCertificateError:

      at Object.throwDecodedError (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.799s
Ran all test suites.`

**Comment by tourdedave** [comment]
Sorry about that. Please open a new issue and follow [the issue template](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md). It will help us troubleshoot your issue.
