### ISSUE TITLE
HELP error "UnsupportedOperationError"

### ISSUE THREAD

**Issue by BB64BIT** [SeleniumHQ/selenium-ide#716]
### **HELP Error**
**UnsupportedOperationError: pointer movements relative to viewport are not supported in bridge mode**

Hi, I’m having some issues with test execution with Selenium side runner.
I create test with Selenium IDE, I start them from IDE and they don’t give me back errors, but if I try to execute tests from Selenium side runner I find these errors:

![Schermata da 2019-06-10 16-32-48](https://user-images.githubusercontent.com/26792466/59255027-96097880-8c31-11e9-8af0-a8383fe4a4bd.png)

```
at executeLegacy (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/input.js:1129:17)
at Actions.perform (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/input.js:971:16
```

Can you help me? Thank you in advance.

Best regards

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
