### ISSUE TITLE
     : Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error:

### ISSUE THREAD

**Issue by shital17jun** [SeleniumHQ/selenium-ide#801]
>selenium-side-runner "form1.side" --timeout 2000 -c "browserName='internet explorer'"
 for running  it gicing error 

    : Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error:

       8 | jest.setTimeout(300000);
       9 | describe("Default Suite", () => {
    > 10 |   it("fsdfd", async () => {
         |   ^
      11 |     await tests["fsdfd"](driver, vars);
      12 |     expect(true).toBeTruthy();
      13 |   });

      at new Spec (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (DefaultSuite.test.js:10:3)

  ● Default Suite › fsdfd

    NoSuchSessionError: session 0f600db4-b734-4a87-b143-3cd9905e2c39 does not exist

      at Object.throwDecodedError (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)

**Comment by shital17jun** [comment]
seleniumd side runner is 3.12 version .

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
