### ISSUE TITLE
Same Test Runs Successful from UI but Failed when run from Command Line.

### ISSUE THREAD

**Issue by ianhe1** [SeleniumHQ/selenium-ide#911]
## 🐛 Bug Report

I have a test case I created through Selenium IDE record and it runs successfully through the IDE. However, when I run the same test case from Selenium IDE Runner command line, the test failed. 

When I look at the failures, I can see that the problem is at the Verify Text step where in the IDE UI run 

See the screenshot below:

![image](https://user-images.githubusercontent.com/29493768/70745508-e56c5680-1cf1-11ea-9e93-07059dde55e2.png)

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:Google Chrome
Browser Version:

**Comment by tourdedave** [comment]
Please provide a SIDE project file to reproduce this.

**Comment by ianhe1** [comment]
I am going to isolate the issue and create a SIDE project for reproducing it and provide it here.

**Comment by ianhe1** [comment]
Here is the SIDE project for reproducing the issue. 
[Bug_Reproduce.zip](https://github.com/SeleniumHQ/selenium-ide/files/4027984/Bug_Reproduce.zip)
1) You can run this SIDE from the IDE UI. You will see the test is successful.
2) Run the same SIDE from commandlin, You will see the failure.

**Comment by ianhe1** [comment]
Any update on this issue?

**Comment by ianhe1** [comment]
Today, when I run the test from command line on the same machine, I cannot even launch the Chrome browser. I see the following error:
I reinstalled the chrome driver of the same version but still get the error. 
---------------------------------------------------------------------------------
C:\Users\Administrator>selenium-side-runner C:\Automation\New_SeleniumIDE\YPSanityTest_2020-02-24.side
info:    Running C:/Automation/New_SeleniumIDE/YPSanityTest_2020-02-24.side

 RUNS  ./YPSanityTestSuite.test.js
 RUNS  ./TestSuite1.test.js

 FAIL  ./YPSanityTestSuite.test.js
  ● Test suite failed to run

    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 78

      at Object.throwDecodedError (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)

 FAIL  ./TestSuite1.test.js
  ● Test suite failed to run

    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 78

      at Object.throwDecodedError (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        4.735s
Ran all test suites.

**Comment by ianhe1** [comment]
The chrome driver issue is resolved. I am still seeing the first issue which is the verify text on the string that contains the return character. For example, this string "This is a text1 \n and text2 continue." will pass in IDE but not be recognized in commandline runner where the string looks like this:
"This is a text1 
 and text2 continue."
As a result, the verifyElementText fails.
