### ISSUE TITLE
Test suite freezes on the test where http-request doesn't finish in 5 minute

### ISSUE THREAD

**Issue by ros-mary** [SeleniumHQ/selenium-ide#916]
## 🐛 Bug Report

I have test suite where each test runs after another. One test uploads zip-file by typing file path in a file field and clicking on a button to send file(post request). Sometimes handling of such upload lasts more than 5 minutes. So when this situation happens test freezes on click command, next tests of the suite doesn't start and execution of suit finishes when time that is sat in the 'Timeout' settings of the current suite is up.

Error log of uploading test:
> TimeoutError: timeout
> (Session info: chrome=66.0.3359.117)
> (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.10.0-957.27.2.el7.x86_64 x86_64)
> at Object.checkLegacyResponse (../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:585:15)
> at parseHttpResponse (../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:551:13)
> at Executor.execute (../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)

## To Reproduce

Create test suite where first test uploads file and some other tests. Run this test suite(in command line with selenium-side-runner) in conditions where uploading takes more than 5 minute.

## Expected behavior

Execution of suit finishes when time that is sat in the 'Timeout' settings of the current suite is up.

## Upload function from my project
![image](https://user-images.githubusercontent.com/16049859/71419136-03856f80-267f-11ea-9565-646ee51cb4d3.png)

## Environment

Selenium IDE Version:  3.16.1
Selenium SIDE Runner Version:  3.13.0
Node version: 11.10.0
Browser: Chrome
Browser Version: 2.38.552522

**Comment by tourdedave** [comment]
If possible, please provide a SIDE project file to reproduce this.

**Comment by ros-mary** [comment]
I cannot add this project because tests were written for site that is not launched.

**Comment by corevo** [comment]
Any reproducer would do, it doesn't have to be the production site, but even if you could create a different script on a public website that will demonstrate it.
