### ISSUE TITLE
Error saving test results to output directory

### ISSUE THREAD

**Issue by Robinson664** [SeleniumHQ/selenium-ide#923]
## 🐛 Bug Report

I want to output my test results to a file [using the steps here](https://selenium.dev/selenium-ide/docs/en/introduction/command-line-runner#output-test-results-to-a-file).  I'm getting an error message that says that that file already exists.

## To Reproduce

I have a simple *.side file that loads a webpage and asserts some text.  There's one test in the suite and it succeeds, but the command fails.  Here's my command:

`selenium-side-runner --output-directory=results --output-format=junit .\OutputTests.side`

## Expected behavior

I expect a JUnit-formatted file in my "results" directory.

## Actual behavior

The command creates an empty "results" directory.  And I get this error message (emphasis mine):

> ~\Desktop> selenium-side-runner --output-directory=results --output-format=junit .\OutputTests.side
> info:    Running ./OutputTests.side
> added 26 packages from 24 contributors in 1.414s
> 
>  RUNS  ./DefaultSuite.test.js
> 
>  RUNS  ./DefaultSuite.test.js
>  PASS  ./DefaultSuite.test.js (5.674s)
>   Default Suite
>     √ testShouldSucceed (1922ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        5.902s, estimated 9s
> Ran all test suites.
> **Error: EEXIST: file already exists, mkdir 'C:\path\results'**
>     at Object.mkdirSync (fs.js:753:3)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:71:13)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:77:24)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)
>     at sync (C:\path\side-suite-httpsdocs.microsoft.comen-us\node_modules\mkdirp\index.js:78:17)

## Project file reproducing this issue (highly encouraged)

I can't attach my *.side file (something with my corp firewall), so I'll paste the file contents below.

## Environment

OS: Windows 10
Selenium IDE Version:  3.16.1
Selenium SIDE Runner Version:  3.16.0
Node version: 10.15.1
Browser: Chrome
Browser Version: 79.0.3945.88 (Official Build) (64-bit)

## Side File Contents

{
  "id": "1a3441fe-6e70-4321-8c3f-e73e085559c4",
  "version": "2.0",
  "name": "https://docs.microsoft.com/en-us/",
  "url": "https://docs.microsoft.com/",
  "tests": [{
    "id": "ccd5adfb-6ed0-4747-8cbc-a69fd6a33961",
    "name": "testShouldSucceed",
    "commands": [{
      "id": "484ee351-1852-4074-b064-d04d5781b30e",
      "comment": "",
      "command": "open",
      "target": "/en-us/",
      "targets": [],
      "value": ""
    }, {
      "id": "f0ce5e98-6321-4ccf-a5e3-54d6bafd4384",
      "comment": "",
      "command": "assertText",
      "target": "css=h1",
      "targets": [
        ["css=h1", "css:finder"],
        ["xpath=//main[@id='main']/section[2]/h1", "xpath:idRelative"],
        ["xpath=//h1", "xpath:position"],
        ["xpath=//h1[contains(.,'Microsoft Docs')]", "xpath:innerText"]
      ],
      "value": "Microsoft Docs"
    }]
  }],
  "suites": [{
    "id": "ec97f806-5b86-4f62-b50b-b90c747e2127",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["ccd5adfb-6ed0-4747-8cbc-a69fd6a33961"]
  }],
  "urls": ["https://docs.microsoft.com/"],
  "plugins": []
}

**Comment by Robinson664** [comment]
I found the problem.  I'd set the project name to "https://docs.microsoft.com/en-us/".  That's not a valid filename.  When I changed that to "pname", it worked as expected.  I'd recommend that you do some input checking to ensure that the project name follows certain rules.  This error message is not helpful.
